name: CircuitBreaker
favicon: null
layout_spectrum: 0.18328733555972576
typography_spectrum: 0.9758757259696722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9517537520732731
  lightness: 0.6310662219766527
  saturation: 0.5834352110978216
  rhythmicContrast: 0.2847869952674955
purpose: []
